title: Bastien Pasdeloup
description: Associate Professor at IMT Atlantique, France. Research in Artificial Intelligence, Deep Learning, Machine Learning, and Graph Signal Processing. Member of BRAIN team, Lab-STICC.
url: "https://bastienpasdeloup.github.io"
baseurl: ""

# Theme settings
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-sitemap
  - jekyll-seo-tag

# Author info
author:
  name: Bastien Pasdeloup
  email: bastien.pasdeloup@imt-atlantique.fr

# Navigation
nav:
  - title: Home
    url: /
  - title: Research
    url: /research
  - title: Teaching
    url: /teaching
  - title: Contact
    url: /contact

# Social links
scholar: https://scholar.google.com/citations?user=dKOgoG4AAAAJ
linkedin: https://fr.linkedin.com/in/bastien-pasdeloup
github: https://github.com/BastienPasdeloup
twitter: https://x.com/BastPasdeloup

# Build settings
markdown: kramdown
highlighter: rouge
